import urllib.request
import xml.etree.ElementTree as ET
import datetime
import os
import time

print("🤖 Waking up ML ArXiv Research Scout...")
time.sleep(1)
print("🌐 Connecting to live ArXiv API data source...")

# Query: Machine Learning (cs.LG) or Info Retrieval (cs.IR) + Keyword: ranking + Max: 3
url = 'http://export.arxiv.org/api/query?search_query=all:ranking+AND+(cat:cs.IR+OR+cat:cs.LG)&sortBy=submittedDate&sortOrder=descending&max_results=3'

try:
    response = urllib.request.urlopen(url)
    data = response.read()
except Exception as e:
    print(f"❌ API Connection Failed: {e}")
    exit(1)

root = ET.fromstring(data)
ns = {'atom': 'http://www.w3.org/2005/Atom'}

papers = []
for entry in root.findall('atom:entry', ns):
    title = entry.find('atom:title', ns).text.strip().replace('\n', ' ')
    summary = entry.find('atom:summary', ns).text.strip().replace('\n', ' ')
    published = entry.find('atom:published', ns).text[:10]
    link = entry.find('atom:id', ns).text
    papers.append({'title': title, 'summary': summary, 'date': published, 'link': link})

print(f"📥 Fetched {len(papers)} highly relevant papers on ML Ranking.")
time.sleep(1)
print("✍️  Synthesizing and writing to research_weekly.md...")

out_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'outputs')
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, 'research_weekly.md')

with open(out_path, 'w', encoding='utf-8') as f:
    f.write("# 📡 Weekly ML Research Scout Report\n\n")
    f.write(f"*Generated by ArXiv Scout Agent on: {datetime.date.today()}*\n\n")
    f.write("| Published Date | Title | Abstract Snapshot | Link |\n")
    f.write("|---|---|---|---|\n")
    for p in papers:
        # truncate summary for the table so it doesn't break formatting
        short_summary = p['summary'][:200] + "..."
        f.write(f"| {p['date']} | **{p['title']}** | {short_summary} | [View Paper]({p['link']}) |\n")

time.sleep(1)
print(f"✅ Mission Accomplished! Output saved to: {out_path}")
